### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::3000

### ISSUE THREAD

**Issue by ngray48** [ngray48/SDEV_255_Final_Project_Group7#4]
I've tried to get this going but I don't know where my brain went. If anyone is brave enough to dive through this and try to help figure out my problems, please do! It isn't linked to a database yet and I think I have most of the .ejs files built, but I could be wrong. I was too scared to delete the .html files that Jarrod made and this is what I'm left with. Any help would be amazing.
Issue is located in the branch labeled "Natalie's-Mess"

**Comment by ngray48** [comment]
Terminal readout when I'm trying to run


node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at Function.listen (C:\Users\njbjj\OneDrive\Documents\WebApplicationFinalProj\node_modules\express\lib\application.js:635:24))
    at Object.<anonymous> (C:\Users\njbjj\OneDrive\Documents\WebApplicationFinalProj\app.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1512:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v18.12.1
[nodemon] app crashed - waiting for file changes before starting...

**Comment by 20020117** [comment]
I meet the same question,do you solve it?
if you can tell me how to solve it,I will be grateful!
